### PR TITLE
#1787: MenasDAO.getDataset backwards compatibility fix

### LINKED ISSUE #1787: MenasDAO.getDataset backwards compatibility fix
## Describe the bug
`MenasDAO#getDataset` method has parameter of `ValidationLevel` which is mandatory and has no default. This is not backwards compatible.

Plus, even if people set `noValidation`, the `noValidation` param is introduced in the URL. In this case, there should be no param in the URL.

## Expected behaviour
`MenasDAO#getDataset` should have a default `ValidationLevel` set to `noValidation` and if `noValidation` is chosen, do not add it to the URL.

### PR DESCRIPTION
**Pull request by benedeki**
* defined `DefaultValidationLevel`
* default value for `validationLevel` in `getDataset`
* if value for validationLevel is equal to DefaultValidationLevel, validation level is not added to query string

Release notes:
MenasDAO.getDataset made backward compatible.

Closes #1787

### CODE REVIEW

**Review by Zejnilovic — APPROVED** [review]
Code reviewed

**Review by AdrianOlosutean — APPROVED** [review]
Looks good(code review)

File: utils/src/main/scala/za/co/absa/enceladus/utils/validation/ValidationLevel.scala [hunk 1]
```diff
@@ -20,5 +20,10 @@ object ValidationLevel extends Enumeration {
 
   final val NoValidation, ForRun, Strictest = Value
 
-  final val NoValidationName = "NoValidation" // This is used in an annotation - for that the type MUST NOT be specified
+  object Constants { // Not to mix with enumeration items
+    final val DefaultValidationLevel:ValidationLevel  = NoValidation
```
Comment (dk1844) [inline utils/src/main/scala/za/co/absa/enceladus/utils/validation/ValidationLevel.scala:24]:
```suggestion
    final val DefaultValidationLevel: ValidationLevel = NoValidation
```

Also, I keep wondering if the existence of `DefaultValidationLevel` is necessary, but sure, why not.

**Review by dk1844 — APPROVED** [review]
LGTM.

File: utils/src/main/scala/za/co/absa/enceladus/utils/validation/ValidationLevel.scala (hunk 1 above)
Comment (benedeki) [reply utils/src/main/scala/za/co/absa/enceladus/utils/validation/ValidationLevel.scala:24]: I think it does. It prevents accidental removal/change without realizing the consequences - at least I believe it does.

**Review by Zejnilovic — APPROVED** [review]
Ran a spark-jobs standardization and custom project

**Review by AdrianOlosutean — APPROVED** [review]

**Review by dk1844 — APPROVED** [review]
LGTM (just read the code)
