### PR TITLE
#1386 Add support for Cobrix '--is-text' option.

### LINKED ISSUE #1390: All fields are null when stardardizing an ASCII text file as 'cobol' format
## Describe the bug
After Standardization is ran on a flat ASCII test file using `rawformat=cobol`, the output dataset contains `null` in all fields, but ones added explicitly by Standardization:

```
scala> spark.read.parquet("/some/path/enceladus_info_date=2020-06-09/enceladus_info_version=1").toJSON.take(1000).foreach(println)
{"errCol":[],"enceladus_record_id":"7477231b-f648-4161-9b8a-34e243bc6921","enceladus_info_date":"2020-06-09","enceladus_info_date_string":"2020-06-09","enceladus_info_version":1}
{"errCol":[],"enceladus_record_id":"e24da98e-50c3-4a26-8fd1-d6580dffc9df","enceladus_info_date":"2020-06-09","enceladus_info_date_string":"2020-06-09","enceladus_info_version":1}
{"errCol":[],"enceladus_record_id":"09b9b30b-7da3-4bc0-a006-801f3d0ea531","enceladus_info_date":"2020-06-09","enceladus_info_date_string":"2020-06-09","enceladus_info_version":1}
{"errCol":[],"enceladus_record_id":"993da28d-566e-4506-a63c-cc8c7ab5b426","enceladus_info_date":"2020-06-09","enceladus_info_date_string":"2020-06-09","enceladus_info_version":1}
{"errCol":[],"enceladus_record_id":"12ae884e-5772-415b-ba91-abc8c71571a5","enceladus_info_date":"2020-06-09","enceladus_info_date_string":"2020-06-09","enceladus_info_version":1}
...
``` 

The same file loads correctly by Cobrix using the same copybook.

## To Reproduce
Run Standardization on a non-empty ASCII text file having 'cobol' as the raw format.

## Expected behaviour
Data should be parsed correctly.

### PR DESCRIPTION
**Pull request by yruslan**
This option helps a lot when loading ASCII text files where records are delimited by EOL character.

P.S. The first build will fail since I forgot to release Cobrix in Sonatype. I'll re-run it in the morning.

Also closes #1390

### CODE REVIEW

File: spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StdCmdConfig.scala [hunk 1]
```diff
@@ -246,6 +246,16 @@ object StdCmdConfig {
             failure("The --is-xcom option is supported only for COBOL data format")
           })
 
+      opt[Boolean]("cobol-is-text").optional().action((value, config) => {
+        config.copy(cobolOptions = cobolSetIsText(config.cobolOptions, value))
+      }).text("Specifies if the mainframe file is ASCII text file")
+        .validate(value =>
+          if (rawFormat.isDefined && rawFormat.get.equalsIgnoreCase("cobol")) {
```
Comment (AdrianOlosutean) [inline spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StdCmdConfig.scala:253]: Maybe `rawFormat.get` could cause NullPointerException

Comment (yruslan) [reply spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StdCmdConfig.scala:253]: It won't since it is validated earlier. The `scopt` way of things is a big ugly, I agree. I'm just following how we handle other cmd parameters. Maybe we can refactor StdCmdConfig in the future.
