### PR TITLE
1409 Fix fixed width format

### LINKED ISSUE #1409: Make fixed-width work again
## Describe the bug
Make fixed-width work again. Currently, we do not supply width to the reader and it is a mandatory field

## To Reproduce
Steps to reproduce the behaviour OR commands run:
1. Run std with a fixed-width format

## Expected behaviour
Fixed-width format works

### PR DESCRIPTION
**Pull request by Zejnilovic**
This PR should fix the previously working `fixed-width` format. It is just adding metadata to a stringified schema and adding `columnNameOfCorruptRecord`. Current `fixed-width` does not support that, it can be added when we revive the library.

NB: The expected files have 2 extra new lines because `.show` generates 2 extra newlines.

Closes #1409

RN Comment: Fixed-width format works again.

### CODE REVIEW

**Comment by Zejnilovic** [comment]
Please comment on your view on the duplicity - it is all in the test suite.

**Comment by benedeki** [comment]
> 
> 
> Please comment on your view on the duplicity - it is all in the test suite.

Code duplicity in test code is not an issue in my book. At least most of the times.

File: spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala [hunk 1]
```diff
@@ -298,11 +298,14 @@ object StandardizationJob {
                                dao: MenasDAO): DataFrame = {
     val numberOfColumns = schema.fields.length
     val dfReaderConfigured = getFormatSpecificReader(cmd, dataset, numberOfColumns)
-    val dfWithSchema = (if (!cmd.rawFormat.equalsIgnoreCase("parquet")
+    val dfWithSchema = (if (cmd.rawFormat.equalsIgnoreCase("fixed-width")) {
```
[the remark this answers is not in the document]
Comment (Zejnilovic) [reply spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala:301]: I don't see the point and find it uglier than plain simple ifs. But I don't mind switching it up.

Do you find this more readable:

```scala
    val finalReader = cmd.rawFormat.toLowerCase() match {
      case "fixed-width" =>
        val inputSchema = PlainSchemaGenerator.generateInputSchema(schema)
        dfReaderConfigured.schema(inputSchema)
      case format if (format != "parquet" && format != "cobol") =>
        // SparkUtils.setUniqueColumnNameOfCorruptRecord is called even if result is not used to avoid conflict
        val columnNameOfCorruptRecord = SparkUtils.setUniqueColumnNameOfCorruptRecord(spark, schema)
        val optColumnNameOfCorruptRecord: Option[String] = if (cmd.failOnInputNotPerSchema) {
          None
        } else {
          Option(columnNameOfCorruptRecord)
        }
        val inputSchema = PlainSchemaGenerator.generateInputSchema(schema, optColumnNameOfCorruptRecord)
        dfReaderConfigured.schema(inputSchema)
      case _ => dfReaderConfigured
    }

```

[the remark this answers is not in the document]
Comment (benedeki) [reply spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala:301]: What about:
```
    val finalReader = cmd.rawFormat.toLowerCase() match {
      case "fixed-width" =>
        val inputSchema = PlainSchemaGenerator.generateInputSchema(schema)
        dfReaderConfigured.schema(inputSchema)
      case "parquet" || "cobol" => dfReaderConfigured
      case _ =>
        // SparkUtils.setUniqueColumnNameOfCorruptRecord is called even if result is not used to avoid conflict
        val columnNameOfCorruptRecord = SparkUtils.setUniqueColumnNameOfCorruptRecord(spark, schema)
        val optColumnNameOfCorruptRecord: Option[String] = if (cmd.failOnInputNotPerSchema) {
          None
        } else {
          Option(columnNameOfCorruptRecord)
        }
        val inputSchema = PlainSchemaGenerator.generateInputSchema(schema, optColumnNameOfCorruptRecord)
        dfReaderConfigured.schema(inputSchema)
```

And many-line default case could be a function, if really to make it compact 😉

[the remark this answers is not in the document]
Comment (Zejnilovic) [reply spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/StandardizationJob.scala]: I tried something, rewrote it even more. Please have a look

**Comment by benedeki** [comment]
Just missing release notes ;-)

File: spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_non_trimmed.txt [hunk 2]
```diff
@@ -0,0 +1,12 @@
++---+---------------+---------+--------------------------------------------------------------------------+
+|id |first_name     |last_name|errCol                                                                    |
++---+---------------+---------+--------------------------------------------------------------------------+
+|0  |Georgina       | Richardt|[[stdCastError, E00000, Standardization Error - Type cast, id, [1  ], []]]|
+|0  |Seamus         |    Klaes|[[stdCastError, E00000, Standardization Error - Type cast, id, [2  ], []]]|
+|0  |Griff          |  Leaning|[[stdCastError, E00000, Standardization Error - Type cast, id, [3  ], []]]|
+|0  |Klarrisa       |    Corps|[[stdCastError, E00000, Standardization Error - Type cast, id, [4  ], []]]|
+|0  |Cornie         |Hewertson|[[stdCastError, E00000, Standardization Error - Type cast, id, [5  ], []]]|
+|0  |Maybeeeeeeeeeee|        a|[[stdCastError, E00000, Standardization Error - Type cast, id, [6  ], []]]|
```
Comment (yruslan) [inline spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_non_trimmed.txt:9]: 👀  Interesting that type casting failed here

Comment (Zejnilovic) [reply spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_non_trimmed.txt:9]: `"  10".toLong` will fail as well. Regardless of the whitespace placement.

Comment (yruslan) [reply spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_non_trimmed.txt:9]: Is it the expected behavior or should we log an issue?

IMHO, the current behavior makes non-trimming mode useless if there are numeric fields in the file.

Comment (benedeki) [reply spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_non_trimmed.txt:9]: > 
> 
> Is it the expected behavior or should we log an issue?
> 
> IMHO, the current behavior makes non-trimming mode useless if there are numeric fields in the file.

Can use pattern, particuarly if the number of digits is fixed. But I agree, the usability is limited.

Comment (Zejnilovic) [reply spark-jobs/src/test/resources/data/standardization_fixed_width_suite_expected_non_trimmed.txt:9]: We all agree it is weird. But the scope of this PR was to make something work again as it was. We can log further issues down the road or when we revive the library
