### PR TITLE
#1337 Fixing missing success case

### LINKED ISSUE #1337: missing success option v StandardizationJob.scala line 336
## Describe the bug
Run standardization fails and the current run is still in running state and in case of success missing log.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Run Standardization job

## Additional context
Log:
```
20/05/14 10:54:48 INFO standardization.StandardizationJob$: Menas API Run URL: http://localhost:8080/menas_war_exploded/api/runs/castingConformanceRule/14/6
20/05/14 10:54:48 INFO standardization.StandardizationJob$: Menas UI Run URL: http://localhost:8080/menas_war_exploded/#/runs/castingConformanceRule/14/6
Exception in thread "main" scala.MatchError: Success(()) (of class scala.util.Success)
	at za.co.absa.enceladus.standardization.StandardizationJob$.handleControlInfoValidation(StandardizationJob.scala:336)
	at za.co.absa.enceladus.standardization.StandardizationJob$.executeStandardization(StandardizationJob.scala:287)
	at za.co.absa.enceladus.standardization.StandardizationJob$.main(StandardizationJob.scala:99)
	at za.co.absa.enceladus.standardization.StandardizationJob.main(StandardizationJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)```

### PR DESCRIPTION
**Pull request by AdrianOlosutean**
Closes #1337

### CODE REVIEW

File: spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala [hunk 1]
```diff
@@ -322,14 +322,17 @@ object DynamicConformanceJob {
 
   private def handleControlInfoValidation(): Unit = {
     ControlInfoValidation.addRawAndSourceRecordCountsToMetadata() match {
-      case Failure(ex: za.co.absa.enceladus.utils.validation.ValidationException) =>
+      case Failure(ex: za.co.absa.enceladus.utils.validation.ValidationException) => {
```
Comment (benedeki) [inline spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/DynamicConformanceJob.scala:325]: Why the full path to the exception class?

**Comment by benedeki** [comment]
When a bug reported by somebody, especially if a tester, it's nice to wait with merge for the confirmation from the particular person, that the test (case) the revealed the bug passes now. 😉
