### PR TITLE
#1974: Conformance doesn't add the Info... columns

### LINKED ISSUE #1974: Conformance doesn't add the `Info...` columns
## Describe the bug
_Conformance_ doesn't add the `Info...` columns: `enceladus_info_date`, `enceladus_info_date_string` and `enceladus_info_version`.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Run _Conformance_
2. Check the output data
3. The columns are not present

## Expected behavior
Columns should be added to the dataset.

### PR DESCRIPTION
**Pull request by benedeki**
* Correct Dataframe used for repartitioning

Closes #1974

### CODE REVIEW

**Review by Zejnilovic — DISMISSED** [review]
Code reviewed

**Review by AdrianOlosutean — DISMISSED** [review]
Tried locally a normal job without using partitioning

**Review by Zejnilovic — APPROVED** [review]

File: spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformanceExecution.scala [hunk 1]
```diff
@@ -162,7 +156,7 @@ trait ConformanceExecution extends CommonJobExecution {
 
     val minBlockSize = configReader.getLongOption(CommonConfConstants.minPartitionSizeKey)
     val maxBlockSize = configReader.getLongOption(CommonConfConstants.maxPartitionSizeKey)
-    val withRepartitioning = repartitionDataFrame(result, minBlockSize, maxBlockSize)
+    val withRepartitioning = repartitionDataFrame(withPartCols, minBlockSize, maxBlockSize)
```
Comment (dk1844) [inline spark-jobs/src/main/scala/za/co/absa/enceladus/conformance/ConformanceExecution.scala:159]: Is my understanding of the PR correct, that this is the problematic place where, originally, the dataframe without `Info*` columns was used?

(Otherwise just extracting to a method etc. is just readablity stuff)

**Review by dk1844 — APPROVED** [review]
LGTM (just read the code)

**Review by AdrianOlosutean — APPROVED** [review]
