### PR TITLE
#1978 icons mixup corrected for filter edit

### LINKED ISSUE #1978: Icons mixup
## Describe the bug
As @kevinwallimann discovered, the filter icons seem a bit mixed up for NOT, Equals and Differs.

## To Reproduce
Steps to reproduce:
1. Open dialog to create a mapping table
2. Filter > Add
## Expected behavior
The Equals icon should be used for Differs, perhaps switch NOT and Differs, too.

## Screenshots
icons-mixup

### PR DESCRIPTION
**Pull request by dk1844**
This PR solves the icons mixup for filter editing mentioned in #1978 :

icons-mixup-before
(⬆️ shows the mixed-up state prior to this PR)

Now, the icons are as intended and also conform to the icons used in filter view.

## Testrun
Filter editing now:
icons-mixup-fix

Filter view (unchanged, just for reference):
filter-view-icons

Closes #1978 

## Suggested RN
Filter edit icons are now switched to better convey their expected meaning and to conform to the icons used in the filter view.

### CODE REVIEW

**Review by kevinwallimann — APPROVED** [review]

**Review by Zejnilovic — APPROVED** [review]

File: menas/ui/service/FilterTreeUtils.js [hunk 1]
```diff
@@ -61,6 +61,10 @@ class FilterTreeUtils {
           filterNode.text = "OR";
           filterNode.icon = "sap-icon://split";
           break;
+        case "NotFilter":
```
Comment (dk1844) [inline menas/ui/service/FilterTreeUtils.js:64]: There is no code change, just reordering of cases - now they are in the same order as the `MenuItem`s in the `filterTreeEdit.fragment`. (The different order was most probably the reason for the mixup, on my end)

**Review by benedeki — APPROVED** [review]

**Review by AdrianOlosutean — APPROVED** [review]
