### PR TITLE
#1393 Add new fixed width project

### LINKED ISSUE #1393: Conflicting dependency on 'enceladus-utils:1.7.0'
## Describe the bug
Currently, `spark-jobs` depends on `enceladus-fixedWidth:1.7.0` which depends on 'enceladus-utils:1.7.0'. This creates a class path conflict between current `utils` module and the old `enceladus-utils` which have the same namespace of packages.

## To Reproduce
Inspect the dependencies of `spark-jobs`.

Or (worked for me, but might not always work since class name resolution might be non-deterministic)

Try to go to the source code of `SparkTestBase` from any unit test suite that uses it.

## Expected behaviour
The `spark-jobs` module should depend only on one version of `utils`.

## Screenshots
Screenshot 2020-06-12 at 09 42 24

## Proposed solution
We can do either of these:
- Remove `enceladus-fixedWith` dependency if nobody uses it.
- Revive `fixed-width` (yes, with the new name) in `enceladus` project.
- Revive `fixed-width` in a separate repository. This might require removing its dependency on Enceladus utils.

### PR DESCRIPTION
**Pull request by Zejnilovic**
Implementation of new FixedWidth project in Enceladus

Added charset, treatEmptyValuesAsNulls and nullValue as spark-job switches

Fixes #1393 

RN: Update version of FIxedWidth and add charset, treatEmptyValuesAsNulls and nullValue options.

### CODE REVIEW

File: spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala [hunk 1]
```diff
@@ -129,20 +133,28 @@ object StandardizationConfigParser {
         config.withRawPathOverride(Some(value)))
         .text("override the path of the raw data (used internally for performance tests)"),
 
+      opt[Boolean]("empty-values-as-nulls").optional()
+        .action((value, config) => config.withFixedWidthTreatEmptyValuesAsNulls(Some(value)))
+        .text("For FixedWidth file format. Treats empty values as null. Default is false"),
```
Comment (dk1844) [inline spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala:138]: The only unclear thing to me is where the defaults are coming from.

File: spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala [hunk 2]
```diff
@@ -129,20 +133,28 @@ object StandardizationConfigParser {
...
+
+      opt[String]("null-value").optional()
+        .action((value, config) => config.withFixedWidthNullValue(Some(value)))
+        .text("""For FixedWidth file format. Sets the representation of a null value. Defaults is ""."""),
```
Comment (dk1844) [inline spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala:142]: dtto

File: spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala (hunk 1 above)
Comment (AdrianOlosutean) [reply spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala:138]: Does it make sense to just have it as Boolean instead of Option[Boolean]?

Comment (Zejnilovic) [reply spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfigParser.scala:138]: The defaults are defaults of the FixedWidth file format. Same as CSV Delimiter, header, etc.

File: spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfig.scala [hunk 3]
```diff
@@ -76,6 +78,8 @@ case class StandardizationConfig(rawFormat: String = "xml",
   override def withPerformanceMetricsFile(value: Option[String]): StandardizationConfig = copy(performanceMetricsFile = value)
   override def withFolderPrefix(value: Option[String]): StandardizationConfig = copy(folderPrefix = value)
   override def withPersistStorageLevel(value: Option[StorageLevel]): StandardizationConfig = copy(persistStorageLevel = value)
+  override def withFixedWidthTreatEmptyValuesAsNulls(value: Option[Boolean]): StandardizationConfig = copy(fixedWidthTreatEmptyValuesAsNulls = value)
```
Comment (benedeki) [inline spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfig.scala:81]: **Minor:** Line too long

File: spark-jobs/src/main/scala/za/co/absa/enceladus/standardization_conformance/config/StandardizationConformanceConfig.scala [hunk 4]
```diff
@@ -82,6 +84,8 @@ case class StandardizationConformanceConfig(datasetName: String = "",
   override def withFixedWidthTrimValues(value: Option[Boolean]): StandardizationConformanceConfig = copy(fixedWidthTrimValues = value)
   override def withRawPathOverride(value: Option[String]): StandardizationConformanceConfig = copy(rawPathOverride = value)
   override def withFailOnInputNotPerSchema(value: Boolean): StandardizationConformanceConfig = copy(failOnInputNotPerSchema = value)
+  override def withFixedWidthTreatEmptyValuesAsNulls(value: Option[Boolean]): StandardizationConformanceConfig = copy(fixedWidthTreatEmptyValuesAsNulls = value)
```
Comment (benedeki) [inline spark-jobs/src/main/scala/za/co/absa/enceladus/standardization_conformance/config/StandardizationConformanceConfig.scala:87]: **Minor:** Line too long

File: spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationFixedWidthSuite.scala [hunk 5]
```diff
@@ -30,7 +30,7 @@ import za.co.absa.enceladus.utils.implicits.DataFrameImplicits.DataFrameEnhancem
 import za.co.absa.enceladus.utils.udf.UDFLibrary
 
 class StandardizationFixedWidthSuite extends FunSuite with SparkTestBase with MockitoSugar{
-  private implicit val udfLibrary:UDFLibrary = new UDFLibrary()
+  private implicit val udfLibrary: UDFLibrary = new UDFLibrary()
   private val log: Logger = LoggerFactory.getLogger(this.getClass)
```
Comment (benedeki) [inline spark-jobs/src/test/scala/za/co/absa/enceladus/standardization/StandardizationFixedWidthSuite.scala:34]: **Original code issue:** In case if you would be fixing the long lines or anything else, the `val log: Logger` is not used.

File: spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfig.scala (hunk 3 above)
Comment (Zejnilovic) [reply spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfig.scala:81]: This is a good place for the exception we allowed ourselves. We said on CQC that a line shouldn't be longer than 120. But if it is justifiable it is ok to go to 140. Now, remember I fought for numbers 80 and 100. But here I think it is justifiable to have it longer since it does not have any "logic". It is just a `copy` method adding that one parameter, 20 times repeating, for different parameters.

Comment (Zejnilovic) [reply spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfig.scala:81]: I take it back, I was on a wrong branch and didn't see this one goes to 150... 🤦

Comment (benedeki) [reply spark-jobs/src/main/scala/za/co/absa/enceladus/standardization/config/StandardizationConfig.scala]: Also in such case it's fine to add a scalastyle ignore rule.
