### PR TITLE
1659 Fix Property Definition Update

### LINKED ISSUE #1659: Import of PropertyDefinition does not update Essentiality
## Describe the bug
When import and presumably update is used on the property definition it does not update essentiality

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. have a property definition
2. update the definition with different essentiality
3. it does not update

## Expected behaviour
I expect it to update

### PR DESCRIPTION
**Pull request by Zejnilovic**
Fixes #1659 

RN: Update and import API of Property Def now properly updates essentiality, putIntoInfoFile and propertyType

### CODE REVIEW

**Review by dk1844 — APPROVED** [review]

File: menas/src/main/scala/za/co/absa/enceladus/menas/services/PropertyDefinitionService.scala [hunk 1]
```diff
@@ -34,7 +34,11 @@ class PropertyDefinitionService @Autowired()(propertyDefMongoRepository: Propert
 
   override def update(username: String, propertyDef: PropertyDefinition): Future[Option[PropertyDefinition]] = {
     super.update(username, propertyDef.name, propertyDef.version) { latest =>
-      latest.setDescription(propertyDef.description)
+      latest
```
Comment (benedeki) [inline menas/src/main/scala/za/co/absa/enceladus/menas/services/PropertyDefinitionService.scala:37]: Why using the setters here, creating 4 new instances, instead of using the copy constructor directly, once, with the four properties?

Comment (Zejnilovic) [reply menas/src/main/scala/za/co/absa/enceladus/menas/services/PropertyDefinitionService.scala:37]: Keeping up with what is already established in dataset, schema and mapping table services

Comment (benedeki) [reply menas/src/main/scala/za/co/absa/enceladus/menas/services/PropertyDefinitionService.scala:37]: Not blocking for sure. Just considered it little ineffective. 😉

**Review by AdrianOlosutean — APPROVED** [review]
LGTM

**Review by lokm01 — APPROVED** [review]
Reviewed the code, looks good.
