### PR TITLE
1820 Fix auditable message for Dataset Properties

### LINKED ISSUE #1820: No changes detected in Dataset when property value is changed
## Describe the bug
When a property is defined or changed in a Dataset, the version is correctly increased. But the audit log show "no changes".

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Have a property defined
2. Open an existing dataset definition
3. Add a value to the property
4. Save the changes
5. See the version increased
6. Go to Audit tab of the Dataset
7. See _No changes_

## Expected behaviour
The changes are properly displayed in the audit log.

## Screenshots
image

### PR DESCRIPTION
**Pull request by Zejnilovic**
**How it looks now:**

image

**Release notes**: 
Now Audit Trail in Menas shows added, removed and changed properties

Fixes #1820

### CODE REVIEW

File: data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala [hunk 1]
```diff
@@ -79,6 +79,74 @@ trait Auditable[T <: Product] { self: T =>
     }).getOrElse(Seq())
   }
 
+
+
+  private[model] def getOptionalMapFieldsAudit(newValue: T, fieldName: AuditFieldName)(implicit ct: ClassTag[T]): Seq[AuditTrailChange] = {
+    def tupleToSomeString(v: (String, _)): Option[String] = Some(s"""key: "${v._1}" value: "${v._2}"""")
```
Comment (benedeki) [inline data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala:85]: **Minor:** The function name is not very informative IMHO. What about `makeAuditTrailChangeValue`? Or anything 😄

File: data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala [hunk 2]
```diff
@@ -79,6 +79,74 @@ trait Auditable[T <: Product] { self: T =>
...
+
+    val index = getFieldIndex(fieldName.declaredField)
+
+    index.map({i =>
+      val maybeNewMap = newValue.productElement(i).asInstanceOf[Option[Map[String, _]]]
+      val maybeOldMap = self.productElement(i).asInstanceOf[Option[Map[String, _]]]
+
+      (maybeNewMap, maybeOldMap) match {
```
Comment (benedeki) [inline data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala:93]: **Suggestion:** This function is rather long. I would put the cases into sub-functions.
* Shorter
* `oldMap.toSet` and `newMap.toSet` wouldn't need to be done multiple times
* The second and the third `case` is code duplication for parts of the first `case`

**Review by benedeki — CHANGES_REQUESTED** [review]
Please change the PR target from `develop`.
The other comments are not requests  to change, just suggestions open to discussion.

File: data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala (hunk 1 above)
Comment (Zejnilovic) [reply data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala:85]: Followed convention of `getPrimitiveFieldsAudit`, `getSeqFieldsAudit`. Would you change these as well?

File: data-model/src/test/scala/za/co/absa/enceladus/model/menas/audit/AuditableTest.scala [hunk 3]
```diff
@@ -75,4 +84,21 @@ class AuditableTest extends AnyFunSuite {
...
+
+  test("Testing changed getOptionalMapFieldsAudit") {
+    val newObj2 = obj2.copy(properties = Some(Map("key1" -> "value previous")))
+    val result = newObj2.getOptionalMapFieldsAudit(obj3, AuditFieldName("properties", "Property"))
+    assertResult(Seq(
+      AuditTrailChange(field = "properties", newValue = Some("""key: "key1" value: "value1""""), oldValue = Some("""key: "key1" value: "value previous""""), message = "Property changed.")
+    ))(result)
+  }
+
+
```
Comment (dk1844) [inline data-model/src/test/scala/za/co/absa/enceladus/model/menas/audit/AuditableTest.scala:103]: I believe the _removed_ test case should also be present.

```suggestion
  test("Testing removed getOptionalMapFieldsAudit") {
    val result = obj3.getOptionalMapFieldsAudit(obj2, AuditFieldName("properties", "Property"))
    assertResult(Seq(
      AuditTrailChange(field = "properties", newValue = None, oldValue = Some("""key: "key1" value: "value1""""), message = "Property removed.")
    ))(result)
  }
```

Comment (dk1844) [reply data-model/src/test/scala/za/co/absa/enceladus/model/menas/audit/AuditableTest.scala:103]: Depending on the rest of the decision, you may want to include the cases for both `properties = Some(Map.empty)|None` for the _added_ and _removed_ test cases, to make sure that you correctly cover the trail creation for these cases, too.

Whether to spell it out and forego some DRYness or use the infamous `Seq(None, Some(Map.empty)).forEach{ props => test(s"almost the same test differentiated by $prop")}` is up to you.

For my brief'n'naive™ testing I have just spelled it out (steal away if it seems useful):
```scala
  test("Testing added getOptionalMapFieldsAudit - explicitly None properties") {
    val result = obj2.copy(properties = None).getOptionalMapFieldsAudit(obj3, AuditFieldName("properties", "Property"))
    assertResult(Seq(
      AuditTrailChange(field = "properties", newValue = Some("""key: "key1" value: "value1""""), oldValue = None, message = "Property added.")
    ))(result)
  }

  test("Testing removed getOptionalMapFieldsAudit  - explicitly None properties") {
    val result = obj3.getOptionalMapFieldsAudit(obj2.copy(properties = None), AuditFieldName("properties", "Property"))
    assertResult(Seq(
      AuditTrailChange(field = "properties", newValue = None, oldValue = Some("""key: "key1" value: "value1""""), message = "Property removed.")
    ))(result)
  }
```

File: data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala (hunk 2 above)
Comment (dk1844) [reply data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala:93]: Agreed on being a bit long.

But I have the feeling that maybe only the first case processing is actually needed (because what is the auditing difference between having `None` vs `Some(Map.empty)`), so this may be a way to shorten it. I hope I am not missing something but would do:

```scala
index.map({ i =>
      // because from AuditTrail perspective None vs Some(Map.empty) yields the same AuditTrail result:
      val newMap = newValue.productElement(i).asInstanceOf[Option[Map[String, _]]].getOrElse(Map.empty)
      val oldMap = self.productElement(i).asInstanceOf[Option[Map[String, _]]].getOrElse(Map.empty)

      val added = ... // same as before
      val removed = ... // same as before
     ...

      val addedList = ... // same as before
      val removedList = ... // same as before
      val changedList = ... // same as before

      removedList ++ addedList ++ changedList
    }).getOrElse(Set.empty).toSeq

```

I believe that after this, the result might already be simple enough. But some sub-functions, as @benedeki suggested, will still be possible, of course. Your call.

**Review by dk1844 — COMMENTED** [review]
- [x] code reviewed
- [x] pulled
- [x] built
- [ ] run
(just ran the `AuditableTest` suite).

Apart from the suggestions, LGTM.

File: data-model/src/test/scala/za/co/absa/enceladus/model/menas/audit/AuditableTest.scala (hunk 3 above)
Comment (Zejnilovic) [reply data-model/src/test/scala/za/co/absa/enceladus/model/menas/audit/AuditableTest.scala:103]: A great catch. Did not notice properties were Empty by default.

File: data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala (hunk 1 above)
Comment (benedeki) [reply data-model/src/main/scala/za/co/absa/enceladus/model/menas/audit/Auditable.scala:85]: Sorry not being clear. No problem with `getOptionalMapFieldsAudit`.
I was talking about `tupleToSomeString`.

**Review by benedeki — APPROVED** [review]
- [x] code reviewed
- [x] pulled
- [x] built
- [x] run

**Review by dk1844 — APPROVED** [review]
LGTM (just read the code)
